config/routes.rb
Rails.application.routes.draw do
  root    'static_pages#home'
  get     '/signup', to: 'users#new'
  post    '/signup', to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  validates :first_name, presence: true,
                         length: { minimum: 3, maximum: 50 }

  validates :last_name, presence: true,
                        length: { minimum: 3, maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true,
                       length: { minimum: 6 }

  validates :password_confirmation, presence: true,
                                    length: { minimum: 6 }


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      flash[:info] = "Tu es déja connecté !"
      redirect_to root_url
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Bon retour, #{user.first_name} !"
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "A bientôt !"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if logged_in?
      @user = User.find(params[:id])
    else
      flash[:danger] = "Bien essayé, petit malin !\nAccès restreint, connectes toi pour en voir plus."
      redirect_to login_url
    end
  end

  def index
    if logged_in?
      @users = User.all
    else
      flash[:danger] = "Bien essayé, petit malin !\nPour voir la liste des membres, tu dois te connecter."
      redirect_to login_url
    end
  end

  def new
    if logged_in?
      flash[:info] = "Tu es déja enregistré !"
      redirect_to root_url
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome in Dat Club !"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    if logged_in?
      if session[:user_id].to_i == params[:id].to_i
        @user = User.find(params[:id])
      else
        flash[:danger] = "Bien essayé, petit malin !\nCe n'est pas ton profil !"
        redirect_to root_url
      end
    else
      flash[:danger] = "Bien essayé, petit malin !\nAccès restreint, connectes toi pour en voir plus."
      redirect_to login_url
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:info] = "Profil mis à jour avec succès"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'StarrK Club'

    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <ul class="nav navbar-nav navbar-left">
      <%= link_to "Dat Private Club", root_path, id: "logo" %>
      <li><%= link_to "Accueil", root_path %></li>
    </ul>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Accès au club", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Mon compte <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profil", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Se déconnecter", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Se connecter", login_path %></li>
          <li><%= link_to "Nous rejoindre", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Le formulaire contient <%= pluralize(@user.errors.count, "erreur") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Accueil") %>

<div class="center jumbotron">
  <h1>Bienvenue in Dat Private Club</h1>

  <% if logged_in? %>
    <%= link_to "Accède au club en cliquant ici !", users_path, class: "btn btn-success" %>
  <% else %>
    <%= link_to "Enregistre toi maintenant au club !", signup_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edition') %>
<h1>Modifie ton profil</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Enregistrer les modifications", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Liste des membres du club</h1>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <table class="table">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Email</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.last_name %></td>
            <td><%= user.first_name %></td>
            <td><%= user.email %></td>
            <td><%= link_to "Voir le profil", user_path(user), class: "btn btn-primary"%></td>
          </tr>
        <% end %>
      </tbody>
    </table
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.first_name %> <%= @user.last_name %></h1>
      <p>Adresse Mail : <%= @user.email %></p>
      <% if @user.id == session[:user_id] %>
        <%= link_to "Modifie ton profil", edit_user_path(@user), class: "btn btn-primary"%>
      <% end %>
    </section>
  </aside>
</div>